### ISSUE TITLE
Make alert expiration time configurable

### ISSUE THREAD

**Issue by ThomasObenaus** [ThomasObenaus/sokar#45]
Currently it's hardcoded.
See: https://github.com/ThomasObenaus/sokar/blob/master/scaleAlertAggregator/scaleAlertPool.go#L46

**Comment by serkas** [comment]
Related alert manager configuration:
```
  - receiver: receiver_name
    match:
      type: autoscaling
      component: CMP
    repeat_interval: 60s  # Equal to the expiration interval
    group_interval: 10s   # Less than repeat_interval
```
